chmod 755 png_inverter.py
chmod +x png_inverter.py
chmod 755 shortcut_text_formatter.py
chmod +x shortcut_text_formatter.py
chmod 755 scan.py
chmod +x scan.py
chmod 755 string_scanner.py
chmod +x string_scanner.py
chmod 755 linux_compatibility.py
chmod +x linux_compatibility.py
chmod 755 image_scale_reducer.py
chmod +x image_scale_reducer.py
chmod 755 clipboard_text_replacer.py
chmod +x clipboard_text_replacer.py
chmod 755 string_counter.py
chmod +x string_counter.py
chmod 755 clipboard_lines_to_string_array.py
chmod +x clipboard_lines_to_string_array.py
chmod 755 scriptboard.py
chmod +x scriptboard.py
chmod 755 clipboard_cvs_to_array.py
chmod +x clipboard_cvs_to_array.py
chmod 755 string_replacer.py
chmod +x string_replacer.py
chmod 755 deprinter.py
chmod +x deprinter.py
chmod 755 ghost_print_remover.py
chmod +x ghost_print_remover.py
chmod 755 list_orderer.py
chmod +x list_orderer.py
chmod 755 bad_text_scanner.py
chmod +x bad_text_scanner.py
